"""The generic, nestable acquisition method and its bindable components.

``Episode`` owns the method loop and tree. Surfaces compose sources, leaves,
result projections, controller functions, compact nested messages, and
post-controller hooks around it.
"""

from .runtime import Controller, ControllerFactory, ControllerRuntime, Path, Scope
from .identities import (
    IDENTITY_VERSION,
    EpisodeRef,
    StructuralPath,
    UnitRef,
    normalize_structural_path,
)
from .episode import (
    END_BOUND_HIT,
    END_EXHAUSTED,
    END_INCOMPLETE,
    END_REASON_UNIT_BOUND,
    END_SOURCE_FAILED,
    END_YIELD_STOP,
    SOURCE_END_KINDS,
    Acquirable,
    Context,
    Contribution,
    Episode,
    EpisodeRecord,
    EpisodeRequest,
    EpisodeTree,
    EpisodeUpdate,
    EpisodeView,
    EpochMutation,
    Grain,
    Leaf,
    ResumeUnit,
    SourceEnd,
    UnitRecord,
    UnitSource,
    UnitView,
    leaves,
)

__all__ = [
    "Path",
    "Scope",
    "Controller",
    "ControllerFactory",
    "ControllerRuntime",
    "IDENTITY_VERSION",
    "EpisodeRef",
    "StructuralPath",
    "UnitRef",
    "normalize_structural_path",
    "END_BOUND_HIT",
    "END_EXHAUSTED",
    "END_INCOMPLETE",
    "END_REASON_UNIT_BOUND",
    "END_SOURCE_FAILED",
    "END_YIELD_STOP",
    "SOURCE_END_KINDS",
    "Acquirable",
    "Context",
    "Contribution",
    "Episode",
    "EpisodeRecord",
    "EpisodeRequest",
    "EpisodeTree",
    "EpisodeUpdate",
    "EpisodeView",
    "EpochMutation",
    "Grain",
    "Leaf",
    "ResumeUnit",
    "SourceEnd",
    "UnitRecord",
    "UnitSource",
    "UnitView",
    "leaves",
]
